In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [26]:
ele=pd.read_csv('elementsE.csv')
ele

,element,energy,natom,Eper_atom,structure,deltaE1,deltaE3,volt1,volt_av,capacity,atomic_mass
0,Mg,-250.234716,2,-125.117358,Li3Mg3O6.xsf,-1.997042,-1.266882,-4.868522,-4.187523,423.779067,24.305
1,Al,-26.648705,4,-6.662176,Li3Al3O6.xsf,-2.901663,-2.191180,-5.126676,-5.033110,406.569732,26.982
2,Ca,-299.382486,4,-74.845622,Li3Ca3O6.xsf,-2.058899,-1.465344,-3.922746,-3.839562,339.177708,40.080
3,Sc,-188.492581,2,-94.246290,Li3Sc3O6.xsf,-3.142941,-2.806694,-4.733716,-4.151683,319.464608,44.956
4,Ti,-357.446257,3,-119.148752,Li3Ti3O6.xsf,-2.831728,-3.121942,-1.956032,-1.961087,308.634177,47.900
5,V,-579.862777,4,-144.965694,Li3V3O6.xsf,-2.479086,-2.503077,-2.266589,-2.407111,298.191848,50.941
6,Cr,-350.791061,2,-175.395531,Li3Cr3O6.xsf,-2.027494,-1.808321,-2.556368,-2.685015,294.732318,51.996
7,Mn,-422.163307,2,-211.081653,Li3Mn3O6.xsf,-1.858743,-1.520279,-2.704126,-2.874136,285.495737,54.938
8,Fe,-500.335709,2,-250.167855,Li3Fe3O6.xsf,-1.818735,-1.420947,-2.681323,-3.012097,282.757826,55.847
9,Co,-1193.050990,4,-298.262748,Li3Co3O6.xsf,-1.717378,-1.159819,-3.194909,-3.390053,273.842195,58.933
10,Ni,-1372.350049,4,-343.087512,Li3Ni3O6.xsf,-1.438955,-0.915149,-3.027165,-3.010373,274.467566,58.710
11,Cu,-1614.038713,4,-403.509678,Li3Cu3O6.xsf,-1.189404,-0.311439,-3.869769,-3.823299,261.516157,63.546
12,Zn,-922.477844,2,-461.238922,Li3Zn3O6.xsf,-1.473191,-0.418212,-4.766500,-4.638125,256.918522,65.380
13,Ga,-3320.078982,8,-415.009873,Li3Ga3O6.xsf,-2.095155,-1.161654,-4.955041,-4.895658,246.656819,69.720
14,Nb,-235.848814,2,-117.924407,Li3Nb3O6.xsf,-2.390679,-2.545638,-2.166107,-1.925803,203.280240,92.906

In [3]:
alv=pd.read_csv('dataAlV.dat',sep='\s+|\s+', header=None)

C:\Users\Birendra Ale Magar\AppData\Local\Temp\ipykernel_24700\3839942708.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  alv=pd.read_csv('dataAlV.dat',sep='\s+|\s+', header=None)

In [11]:
alv.rename(columns={0: 'structure', 1: 'steps', 2: 'formula', 3: 'a', 4: 'b', 5: 'c', 6: 'alpha', 7: 'beta', 8: 'gamma', 9: 'volume', 10: 'energy(Ry)'}, inplace=True)
alv

,structure,steps,formula,a,b,c,alpha,beta,gamma,volume,energy(Ry)
0,Al6V6,1,Li12Al6V6O24.xsf,5.44793,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411
1,Al6V6,3,Al6V6O24.xsf,5.66600,5.70108,14.44699,90.5643,90.1982,119.7955,404.941306,-1686.430343
2,Al7V5,1,Li12Al7V5O24.xsf,5.66596,5.54797,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943
3,Al7V5,3,Al7V5O24.xsf,5.66028,5.66807,14.13428,90.0000,90.0063,120.0455,392.534491,-1547.826468
4,Al8V4,1,Li12Al8V4O24.xsf,5.65285,5.58988,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870
5,Al8V4,3,Al8V4O24.xsf,5.74123,5.73110,15.38908,73.8151,101.7297,120.4157,418.178406,-1409.526989
6,Al9V3,1,Li12Al9V3O24.xsf,5.63782,5.57691,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681
7,Al9V3,3,Al9V3O24.xsf,5.72162,5.74981,13.57885,90.0000,84.6139,120.1631,383.950154,-1271.106811
8,Al10V2,1,Li12Al10V2O24.xsf,5.64798,5.57966,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038
9,Al10V2,3,Al10V2O24.xsf,5.76381,5.76043,14.59570,90.0000,77.3939,119.9806,406.220920,-1132.701407
10,Al11V,1,Li12Al11VO24.xsf,5.63018,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580
11,Al11V,3,Al11VO24.xsf,5.79008,5.79008,12.18809,90.0000,90.0000,120.0000,353.863747,-993.776096

In [46]:
df1 = alv[alv['steps']==1]
df1.rename(columns={  'volume': 'v', 'energy(Ry)': 'e'}, inplace=True)
df1 = df1.drop(['b'],axis=1)
df1

C:\Users\Birendra Ale Magar\AppData\Local\Temp\ipykernel_24700\3465026347.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.rename(columns={  'volume': 'v', 'energy(Ry)': 'e'}, inplace=True)

,structure,steps,formula,a,c,alpha,beta,gamma,v,e
0,Al6V6,1,Li12Al6V6O24.xsf,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411
2,Al7V5,1,Li12Al7V5O24.xsf,5.66596,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943
4,Al8V4,1,Li12Al8V4O24.xsf,5.65285,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870
6,Al9V3,1,Li12Al9V3O24.xsf,5.63782,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681
8,Al10V2,1,Li12Al10V2O24.xsf,5.64798,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038
10,Al11V,1,Li12Al11VO24.xsf,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580

In [47]:
df1

,structure,steps,formula,a,c,alpha,beta,gamma,v,e
0,Al6V6,1,Li12Al6V6O24.xsf,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411
2,Al7V5,1,Li12Al7V5O24.xsf,5.66596,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943
4,Al8V4,1,Li12Al8V4O24.xsf,5.65285,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870
6,Al9V3,1,Li12Al9V3O24.xsf,5.63782,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681
8,Al10V2,1,Li12Al10V2O24.xsf,5.64798,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038
10,Al11V,1,Li12Al11VO24.xsf,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580

In [48]:
df3 = alv[alv['steps']==3]
df3.rename(columns={ 'a': 'a3', 'c': 'c3','alpha': 'alpha3', 'beta': 'beta3', 'gamma': 'gamma3', 'volume': 'v3', 'energy(Ry)': 'e3'}, inplace=True)
df3 = df3.drop(['b'],axis=1)
df3

C:\Users\Birendra Ale Magar\AppData\Local\Temp\ipykernel_24700\761008082.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns={ 'a': 'a3', 'c': 'c3','alpha': 'alpha3', 'beta': 'beta3', 'gamma': 'gamma3', 'volume': 'v3', 'energy(Ry)': 'e3'}, inplace=True)

,structure,steps,formula,a3,c3,alpha3,beta3,gamma3,v3,e3
1,Al6V6,3,Al6V6O24.xsf,5.66600,14.44699,90.5643,90.1982,119.7955,404.941306,-1686.430343
3,Al7V5,3,Al7V5O24.xsf,5.66028,14.13428,90.0000,90.0063,120.0455,392.534491,-1547.826468
5,Al8V4,3,Al8V4O24.xsf,5.74123,15.38908,73.8151,101.7297,120.4157,418.178406,-1409.526989
7,Al9V3,3,Al9V3O24.xsf,5.72162,13.57885,90.0000,84.6139,120.1631,383.950154,-1271.106811
9,Al10V2,3,Al10V2O24.xsf,5.76381,14.59570,90.0000,77.3939,119.9806,406.220920,-1132.701407
11,Al11V,3,Al11VO24.xsf,5.79008,12.18809,90.0000,90.0000,120.0000,353.863747,-993.776096

In [49]:
df1['a3']=df3['a3'].values
df1['c3']=df3['c3'].values
df1['v3']=df3['v3'].values
df1['e3']=df3['e3'].values

In [50]:
df1

,structure,steps,formula,a,c,alpha,beta,gamma,v,e,a3,c3,v3,e3
0,Al6V6,1,Li12Al6V6O24.xsf,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411,5.66600,14.44699,404.941306,-1686.430343
2,Al7V5,1,Li12Al7V5O24.xsf,5.66596,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943,5.66028,14.13428,392.534491,-1547.826468
4,Al8V4,1,Li12Al8V4O24.xsf,5.65285,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870,5.74123,15.38908,418.178406,-1409.526989
6,Al9V3,1,Li12Al9V3O24.xsf,5.63782,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681,5.72162,13.57885,383.950154,-1271.106811
8,Al10V2,1,Li12Al10V2O24.xsf,5.64798,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038,5.76381,14.59570,406.220920,-1132.701407
10,Al11V,1,Li12Al11VO24.xsf,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580,5.79008,12.18809,353.863747,-993.776096

In [51]:
df1['delta_a'] = -(df1['a']-df1['a3'])*100/df1['a']
df1['delta_c'] = -(df1['c']-df1['c3'])*100/df1['c']
df1['delta_v'] = -(df1['v']-df1['v3'])*100/df1['v']

In [52]:
df1

,structure,steps,formula,a,c,alpha,beta,gamma,v,e,a3,c3,v3,e3,delta_a,delta_c,delta_v
0,Al6V6,1,Li12Al6V6O24.xsf,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411,5.66600,14.44699,404.941306,-1686.430343,4.002805,-1.200814,7.739509
2,Al7V5,1,Li12Al7V5O24.xsf,5.66596,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943,5.66028,14.13428,392.534491,-1547.826468,-0.100248,-2.032572,-0.737468
4,Al8V4,1,Li12Al8V4O24.xsf,5.65285,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870,5.74123,15.38908,418.178406,-1409.526989,1.563459,7.092315,5.956968
6,Al9V3,1,Li12Al9V3O24.xsf,5.63782,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681,5.72162,13.57885,383.950154,-1271.106811,1.486390,-5.319831,-2.031548
8,Al10V2,1,Li12Al10V2O24.xsf,5.64798,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038,5.76381,14.59570,406.220920,-1132.701407,2.050822,2.408861,4.018666
10,Al11V,1,Li12Al11VO24.xsf,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580,5.79008,12.18809,353.863747,-993.776096,2.840051,-14.184939,-9.241096

In [53]:
Li   =    -129.34419679/9
o = -256.511036/8
ry=13.6057
df1['deltaE1'] = ry*(df123['e'].values-3*ele['Eper_atom'].values - 3*Li - 6*o)/12
df1['deltaE3'] = ry*(df123['e3'].values-3*ele['Eper_atom'].values - 0*Li - 6*o)/9
#df1['volt1'] = ry*(df123['e'].values- df123['e1'].values - 1*Li)/1
df1['volt_av'] = ry*(df123['e'].values- df123['e3'].values - 3*Li)/3

NameError: name 'df123' is not defined

In [54]:
import re


elements=[]
for i in range(0,len(df1['formula'])):
    lst=[]

    my_str = str(df1['formula'].values[i][:-6])
    my_list = re.split(r'(\d+)', my_str)
    lst.append(my_list[2])
    lst.append(my_list[2])
    lst.append(my_list[4])

    
    elements.append(lst)

In [55]:
elements=[['Al', 'Al','Al', 'Al','Al', 'Al', 'V', 'V', 'V', 'V', 'V', 'V'],
 ['Al', 'Al','Al', 'Al','Al', 'Al','Al', 'V', 'V', 'V', 'V', 'V'],
 ['Al', 'Al','Al', 'Al','Al', 'Al','Al', 'Al', 'V', 'V', 'V', 'V'],
 ['Al', 'Al','Al', 'Al','Al', 'Al','Al', 'Al', 'Al', 'V', 'V', 'V'],
 ['Al', 'Al','Al', 'Al','Al', 'Al','Al', 'Al', 'Al', 'Al', 'V', 'V'],
 ['Al', 'Al','Al', 'Al','Al', 'Al','Al', 'Al', 'Al', 'Al','Al', 'V']]

In [56]:
df1['structure'] = elements
df1.rename(columns={'structure':'elements'}, inplace=True)
df1=df1.drop(['steps'],axis=1)

In [57]:
df1

,elements,formula,a,c,alpha,beta,gamma,v,e,a3,c3,v3,e3,delta_a,delta_c,delta_v
0,"[Al, Al, Al, Al, Al, Al, V, V, V, V, V, V]",Li12Al6V6O24.xsf,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411,5.66600,14.44699,404.941306,-1686.430343,4.002805,-1.200814,7.739509
2,"[Al, Al, Al, Al, Al, Al, Al, V, V, V, V, V]",Li12Al7V5O24.xsf,5.66596,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943,5.66028,14.13428,392.534491,-1547.826468,-0.100248,-2.032572,-0.737468
4,"[Al, Al, Al, Al, Al, Al, Al, Al, V, V, V, V]",Li12Al8V4O24.xsf,5.65285,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870,5.74123,15.38908,418.178406,-1409.526989,1.563459,7.092315,5.956968
6,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, V, V, V]",Li12Al9V3O24.xsf,5.63782,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681,5.72162,13.57885,383.950154,-1271.106811,1.486390,-5.319831,-2.031548
8,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, V, V]",Li12Al10V2O24.xsf,5.64798,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038,5.76381,14.59570,406.220920,-1132.701407,2.050822,2.408861,4.018666
10,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, V]",Li12Al11VO24.xsf,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580,5.79008,12.18809,353.863747,-993.776096,2.840051,-14.184939,-9.241096

In [67]:

Li   =    -129.34419679/9
o = -256.511036/8
ry=13.6057
deltaE1=[]
deltaE3=[]
#df1['volt1'] = ry*(df1['e'].values- df1['e1'].values - 1*Li)/1
df1['volt_av'] = -ry*(df1['e'].values- df1['e3'].values - 12*Li)/12

for i in range(0, len(df1['elements'])):  #   len(df1['elements'])
    esum=0
    for j in range(0, len(df1['elements'].values[i])):
       # print(df1['elements'].values[i][j])
        
       # print(i)
       # print(j)

        esum += (ele.loc[ele['element']== str((df1['elements'].values[i][j]))  ]['Eper_atom'].values)[0]  

  #  print(df1['e'].values[i])
    de1=ry*(df1['e'].values[i] - esum - 12*Li-24*o)/48
    de3=ry*(df1['e3'].values[i] - esum -24*o)/36

    deltaE1.append(de1)
    deltaE3.append(de3)

df1['deltaE1'] = deltaE1
df1['deltaE3'] = deltaE3

In [68]:
df1

,elements,formula,a,c,alpha,beta,gamma,v,e,a3,c3,v3,e3,delta_a,delta_c,delta_v,volt_av,deltaE1,deltaE3
0,"[Al, Al, Al, Al, Al, Al, V, V, V, V, V, V]",Li12Al6V6O24.xsf,5.44793,14.62258,90.0000,90.0000,120.0000,375.852193,-1861.230411,5.66600,14.44699,404.941306,-1686.430343,4.002805,-1.200814,7.739509,2.654403,-2.684617,-2.694689
2,"[Al, Al, Al, Al, Al, Al, Al, V, V, V, V, V]",Li12Al7V5O24.xsf,5.66596,14.42753,90.0000,90.0041,119.3135,395.450816,-1723.051943,5.66028,14.13428,392.534491,-1547.826468,-0.100248,-2.032572,-0.737468,3.136732,-2.720063,-2.581173
4,"[Al, Al, Al, Al, Al, Al, Al, Al, V, V, V, V]",Li12Al8V4O24.xsf,5.65285,14.36992,89.9838,90.0038,119.6369,394.668149,-1584.860870,5.74123,15.38908,418.178406,-1409.526989,1.563459,7.092315,5.956968,3.259645,-2.751936,-2.582699
6,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, V, V, V]",Li12Al9V3O24.xsf,5.63782,14.34181,90.0000,89.8962,119.6432,391.912036,-1446.735681,5.72162,13.57885,383.950154,-1271.106811,1.486390,-5.319831,-2.031548,3.594105,-2.802483,-2.538609
8,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, V, V]",Li12Al10V2O24.xsf,5.64798,14.25238,90.0000,89.8817,119.6007,390.526947,-1308.452038,5.76381,14.59570,406.220920,-1132.701407,2.050822,2.408861,4.018666,3.732159,-2.808117,-2.500103
10,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, V]",Li12Al11VO24.xsf,5.63018,14.20274,90.0000,90.0000,120.0000,389.894250,-1170.277580,5.79008,12.18809,353.863747,-993.776096,2.840051,-14.184939,-9.241096,4.583482,-2.844699,-2.265105

In [69]:
df1.columns

Index(['elements', 'formula', 'a', 'c', 'alpha', 'beta', 'gamma', 'v', 'e',
       'a3', 'c3', 'v3', 'e3', 'delta_a', 'delta_c', 'delta_v', 'volt_av',
       'deltaE1', 'deltaE3'],
      dtype='object')

In [72]:
df2=df1.iloc[:,[0, 16, 17,18, 2, 9, 13, 3, 10, 14, 7, 11, 15, 4,5,6,1, 8, 12]]

In [73]:
df2

,elements,volt_av,deltaE1,deltaE3,a,a3,delta_a,c,c3,delta_c,v,v3,delta_v,alpha,beta,gamma,formula,e,e3
0,"[Al, Al, Al, Al, Al, Al, V, V, V, V, V, V]",2.654403,-2.684617,-2.694689,5.44793,5.66600,4.002805,14.62258,14.44699,-1.200814,375.852193,404.941306,7.739509,90.0000,90.0000,120.0000,Li12Al6V6O24.xsf,-1861.230411,-1686.430343
2,"[Al, Al, Al, Al, Al, Al, Al, V, V, V, V, V]",3.136732,-2.720063,-2.581173,5.66596,5.66028,-0.100248,14.42753,14.13428,-2.032572,395.450816,392.534491,-0.737468,90.0000,90.0041,119.3135,Li12Al7V5O24.xsf,-1723.051943,-1547.826468
4,"[Al, Al, Al, Al, Al, Al, Al, Al, V, V, V, V]",3.259645,-2.751936,-2.582699,5.65285,5.74123,1.563459,14.36992,15.38908,7.092315,394.668149,418.178406,5.956968,89.9838,90.0038,119.6369,Li12Al8V4O24.xsf,-1584.860870,-1409.526989
6,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, V, V, V]",3.594105,-2.802483,-2.538609,5.63782,5.72162,1.486390,14.34181,13.57885,-5.319831,391.912036,383.950154,-2.031548,90.0000,89.8962,119.6432,Li12Al9V3O24.xsf,-1446.735681,-1271.106811
8,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, V, V]",3.732159,-2.808117,-2.500103,5.64798,5.76381,2.050822,14.25238,14.59570,2.408861,390.526947,406.220920,4.018666,90.0000,89.8817,119.6007,Li12Al10V2O24.xsf,-1308.452038,-1132.701407
10,"[Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, Al, V]",4.583482,-2.844699,-2.265105,5.63018,5.79008,2.840051,14.20274,12.18809,-14.184939,389.894250,353.863747,-9.241096,90.0000,90.0000,120.0000,Li12Al11VO24.xsf,-1170.277580,-993.776096

In [74]:
df2.to_csv('DFT_AlnVm.csv', index=None)